name: fcc CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -C fcc
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make test
      run: make -C fcc test
    - name: coverage
      uses: threeal/gcovr-action@v1.2.0
      with:
        excludes: 'fcc/unit/unit*.c'
